name: Frontend CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        
        - name: Use Node.js
        uses: actions/setup-node@v3
        with:
            node-version: '16'       

        - name: Install Dependencies
        run: npm ci
            working-directory: ./RestaurantSystem.FrontEnd

        - name: Build
            run: npm run build
            working-directory: ./RestaurantSystem.FrontEnd

        - name: Run Tests
            run: npm test
            working-directory: ./RestaurantSystem.FrontEnd
                